### ISSUE TITLE
Need to rename Type Parameter

### ISSUE THREAD

**Issue by micah686** [Nikey646/VndbSharp#3] opened 2017-01-10 03:41 UTC
The inner and outer classes on the NullToEnumConverter.cs have the same names. The outer class at line 7 seems to be conflicting with the inner class at line 31. 

Visual Studio or Resharper is throwing this error.

**Comment by Nikey646** [comment] 2017-01-10 06:47
Not sure what you mean? I'm able to compile it perfectly fine. I do get a Warning indicating that It has the same name as the outer type, but that doesn't stop it from compiling, and it still works as intended?

Do you have Treat Warnings as Errors turned on? That may be causing the issue. In any case, I'll rename the EnumConverters generic type to `TInnerEnum`, although personally i think it makes more sense to leave it as TEnum, even if the Outer Type has the same generic type name.

**Comment by Nikey646** [comment] 2017-01-10 09:59
f57a1ca Should solve this issue btw, if it does go ahead and close the issue~

**Closed** 2017-01-11 02:07 UTC
